name: DockerPushWorkflow

on:
  push:
    tags:
      - "*"

env:
  IMAGE: bozdoz/docker-push

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: |
          docker build -t img .
          docker tag img ${IMAGE}:latest
          docker tag img ${IMAGE}:${{ github.ref_name }}
          # docker push ${IMAGE}:latest
