name: DockerPushWorkflow

on:
  push:
    tags:
      - "*"

env:
  IMAGE: bozdoz/docker-push

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: |
          docker build -t img .

          # ex: v1.2.3-very-good-tag
          TAG="${{ github.ref_name }}"
          # ex: 1.2.3-very-good-tag
          VER=$(echo $TAG | sed "s/^v//g")
          # ex: 1.2.3
          NUM=$(echo $VER | sed "s/\-.*//g")

          docker tag img ${IMAGE}:latest
          docker tag img ${IMAGE}:${NUM}
          docker push ${IMAGE}:latest
          docker push ${IMAGE}:${NUM}

          if [ "$VER" != "$NUM" ]; then
            # publish the full Version if it's not just a number
            docker tag img ${IMAGE}:${VER}
            docker push ${IMAGE}:${VER}
          fi
